/*
 * A_home.java
 *
 * Created on December 6, 2010, 1:25 AM
 */

package Forms;
import Database.*;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
/**
 *
 * @author  adima
 */
public class A_home extends javax.swing.JFrame {
    Dbprocess dp=new Dbprocess();
    Vector v=new Vector();
    int i=0;
    String s;
    public static Vector u_list=new Vector();
    /** Creates new form A_home */
 public A_home(){
     initComponents();
     Point center=GraphicsEnvironment.getLocalGraphicsEnvironment().getCenterPoint();
        int wid = getWidth();
        int heig = getHeight();
        setBounds(center.x - wid / 2, center.y - heig / 2, wid, heig);
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            u_list=dp.getList();
        }
        catch (Exception e)
        {
            System.out.println("Exception "+e);
        }
     v=dp.listUsers("0");
     i=v.size();
    s=i+"";
    pndng.setText(s);
 }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        View = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pndng = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ClientList = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        ManageClients = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        Updates = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ViewImagePool = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        UpdateImagePool = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        UploadImage = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        ChangePass = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        Logout = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 640));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("Welcome admin");

        View.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        View.setForeground(new java.awt.Color(51, 51, 51));
        View.setText("View");
        View.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), null));
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Pending Requests : ");

        pndng.setEditable(false);
        pndng.setFont(new java.awt.Font("Cambria", 3, 14));
        pndng.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pndng.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pndng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pndngActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\Sreedutt\\My Documents\\NetBeansProjects\\Collage Steganography\\src\\Forms\\Img\\images.jpg")); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), null));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu1.setForeground(new java.awt.Color(102, 102, 102));
        jMenu1.setText("Clients");

        ClientList.setText("Client List");
        ClientList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientListActionPerformed(evt);
            }
        });
        jMenu1.add(ClientList);
        jMenu1.add(jSeparator1);

        ManageClients.setText("Manage Clients");
        ManageClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageClientsActionPerformed(evt);
            }
        });
        jMenu1.add(ManageClients);
        jMenu1.add(jSeparator2);

        Updates.setText("Updates");
        Updates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatesActionPerformed(evt);
            }
        });
        jMenu1.add(Updates);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu2.setForeground(new java.awt.Color(102, 102, 102));
        jMenu2.setText("Image Pool");

        ViewImagePool.setText("View ImagePool");
        ViewImagePool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewImagePoolActionPerformed(evt);
            }
        });
        jMenu2.add(ViewImagePool);
        jMenu2.add(jSeparator3);

        UpdateImagePool.setText("Update ImagePool");
        UpdateImagePool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateImagePoolActionPerformed(evt);
            }
        });
        jMenu2.add(UpdateImagePool);
        jMenu2.add(jSeparator4);

        UploadImage.setText("Upload Image");
        UploadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadImageActionPerformed(evt);
            }
        });
        jMenu2.add(UploadImage);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(255, 255, 255));
        jMenu3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu3.setForeground(new java.awt.Color(102, 102, 102));
        jMenu3.setText("Settings");

        ChangePass.setText("Change Password");
        ChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePassActionPerformed(evt);
            }
        });
        jMenu3.add(ChangePass);
        jMenu3.add(jSeparator5);

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jMenu3.add(Logout);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pndng, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(View, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(281, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(pndng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(View)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void UpdateImagePoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateImagePoolActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
    new UpdateImagePool().setVisible(true);
}//GEN-LAST:event_UpdateImagePoolActionPerformed

private void UploadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadImageActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
    new UploadImg().setVisible(true);
}//GEN-LAST:event_UploadImageActionPerformed

private void ChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePassActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
    new ChangePassword().setVisible(true);
}//GEN-LAST:event_ChangePassActionPerformed

private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
    new Login().setVisible(true);
}//GEN-LAST:event_LogoutActionPerformed

private void ClientListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientListActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
    new ClientList().setVisible(true);
}//GEN-LAST:event_ClientListActionPerformed

private void ManageClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageClientsActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
    new ManageClient().setVisible(true);
}//GEN-LAST:event_ManageClientsActionPerformed

private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
// TODO add your handling code here:true
    this.setVisible(false);
    new Requests().setVisible(true);
}//GEN-LAST:event_ViewActionPerformed

private void pndngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pndngActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_pndngActionPerformed

private void ViewImagePoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewImagePoolActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
    new ViewImagePool().setVisible(true);
}//GEN-LAST:event_ViewImagePoolActionPerformed

private void UpdatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatesActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
    new Updates().setVisible(true);
}//GEN-LAST:event_UpdatesActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A_home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ChangePass;
    private javax.swing.JMenuItem ClientList;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JMenuItem ManageClients;
    private javax.swing.JMenuItem UpdateImagePool;
    private javax.swing.JMenuItem Updates;
    private javax.swing.JMenuItem UploadImage;
    private javax.swing.JButton View;
    private javax.swing.JMenuItem ViewImagePool;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JTextField pndng;
    // End of variables declaration//GEN-END:variables

}
