/*
 * MessageOut.java
 *
 * Created on December 31, 2010, 6:22 PM
 */

package com.collage.forms;

import com.collage.image.ImageFinder;

import javax.swing.*;
import java.awt.*;
import java.io.File;

/**
 * @author adima
 */
public class MessageOut extends javax.swing.JFrame {

    /**
     * Creates new form MessageOut
     */
    public MessageOut() {
        initComponents();
        Point center = GraphicsEnvironment.getLocalGraphicsEnvironment().getCenterPoint();
        int wid = getWidth();
        int heig = getHeight();
        setBounds(center.x - wid / 2, center.y - heig / 2, wid, heig);
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            String r = new Sent().r_name;
            //System.out.println(r);
            receiver.setText(r.substring(r.indexOf(" ")).trim());
            String[] t = r.substring(0, r.indexOf(" ")).trim().split("-");
            for (int i = 0; i < 3; i++) {
                if (t[i].length() == 1) {
                    t[i] = "0" + t[i];
                }
            }
            time.setText(t[0] + ":" + t[1] + ":" + t[2]);
            mess_txt.setText(new ImageFinder().getMessage("./sent/" + Login.getUsername() + "/" + new Sent().r_name
                    + ".jpg"));
            //System.out.println("./sent/"+new Login().username+"/"+new Sent().r_name+".jpg");
        } catch (Exception e) {
            System.out.println("Exception " + e);
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        receiver = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mess_txt = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        DeleteMess = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        receiver.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        receiver.setBorder(null);
        receiver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel1.setText("Sent to");

        mess_txt.setColumns(20);
        mess_txt.setRows(5);
        jScrollPane1.setViewportView(mess_txt);

        jLabel2.setText("@");

        time.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        time.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel3.setText("Message");

        Back.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        Back.setForeground(new java.awt.Color(51, 51, 51));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        DeleteMess.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        DeleteMess.setForeground(new java.awt.Color(51, 51, 51));
        DeleteMess.setText("Delete Message");
        DeleteMess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteMessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(receiver, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax
                                                .swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel2)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement
                                                                .UNRELATED)
                                                        .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment
                                                        .LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax
                                                        .swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(71, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(108, Short.MAX_VALUE)
                                .addComponent(Back)
                                .addGap(31, 31, 31)
                                .addComponent(DeleteMess)
                                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(receiver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing
                                                .GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax
                                                .swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing
                                                .GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(DeleteMess)
                                        .addComponent(Back))
                                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void receiverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiverActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_receiverActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
// TODO add your handling code here:
        this.setVisible(false);
        new Sent().setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void DeleteMessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteMessActionPerformed
// TODO add your handling code here:
        File f = new File("./sent/" + Login.getUsername() + "/" + new Sent().r_name + ".jpg");
        f.delete();
        JOptionPane.showMessageDialog(null, "Message Deleted");
        this.setVisible(false);
        new Sent().setVisible(true);
    }//GEN-LAST:event_DeleteMessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MessageOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton DeleteMess;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mess_txt;
    private javax.swing.JTextField receiver;
    private javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables

}
